
services:
  metrics_calculator:
    tty: true
    build: .
    container_name: metrics_calculator
    volumes:
    - $PWD/metrics_calculation:/workspace
    networks:
    - powerbi-network
    ports:
    - 4040:4040
    environment:
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_REMOTE_SOURCE=${MYSQL_REMOTE_SOURCE}
    depends_on:
    - remote_mysql
  
  remote_mysql:
    image: mysql:9.2.0
    container_name: remote_mysql
    volumes:
    - mysql-db-volume:/var/lib/mysql
    - $PWD/remote_dump:/remote_dump
    ports:
    - 3307:3306
    networks:
    - powerbi-network
    environment:
    - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_REMOTE_SOURCE=${MYSQL_REMOTE_SOURCE}

volumes:
  mysql-db-volume:

networks:
  powerbi-network:
    driver: bridge